# Generated by Django 5.2 on 2026-05-19 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Nubank, MercadoPago, Inter', max_length=100, verbose_name='Nome do cartão')),
                ('last_digits', models.CharField(blank=True, default='', max_length=4, verbose_name='Últimos 4 dígitos')),
                ('brand', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express'), ('HIPERCARD', 'Hipercard'), ('OTHER', 'Outra')], default='VISA', max_length=20, verbose_name='Bandeira')),
                ('color', models.CharField(default='#8b5cf6', help_text='Cor hexadecimal para identificação visual', max_length=7, verbose_name='Cor')),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês em que a fatura vence', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de vencimento')),
                ('closing_day', models.PositiveSmallIntegerField(default=3, help_text='Dia do mês em que a fatura fecha', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de fechamento')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor acumulado')),
                ('deadline', models.DateField(verbose_name='Data limite')),
                ('color', models.CharField(default='#22c55e', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#6366f1', help_text='Cor hexadecimal (ex: #6366f1)', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo atual')),
                ('balance_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de referência')),
            ],
            options={
                'verbose_name': 'Configurações',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], default='EXPENSE', max_length=10, verbose_name='Tipo')),
                ('recurrence_type', models.CharField(choices=[('MONTHLY', 'Mensal (recorrente)'), ('INSTALLMENT', 'Parcelado')], max_length=15, verbose_name='Recorrência')),
                ('total_installments', models.PositiveIntegerField(blank=True, help_text='Apenas para parcelado. Ex: 12', null=True, verbose_name='Total de parcelas')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, help_text='Calculado automaticamente para parcelados', null=True, verbose_name='Data de término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='core.creditcard', verbose_name='Cartão')),
                ('tags', models.ManyToManyField(blank=True, related_name='recurring_rules', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Regra Recorrente',
                'verbose_name_plural': 'Regras Recorrentes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', max_length=10, verbose_name='Status')),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='Número da parcela (ex: 3 de 12)', null=True, verbose_name='Parcela nº')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.creditcard', verbose_name='Cartão')),
                ('recurring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.recurringrule', verbose_name='Regra recorrente')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['due_date', '-amount'],
            },
        ),
    ]
