# Generated by Django 5.2 on 2026-06-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringrule',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='core.goal', verbose_name='Meta vinculada'),
        ),
    ]
