# Generated by Django 5.2 on 2026-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurringrule_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
