# Generated by Django 5.2 on 2026-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_goal_is_archived_recurringrule_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto do dinheiro guardado já foi gasto no propósito da meta.', max_digits=12, verbose_name='Valor utilizado'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='funded_by_goal',
            field=models.BooleanField(default=False, help_text='Se True, esta despesa foi paga com dinheiro já guardado na meta e não afeta o fluxo de caixa.', verbose_name='Financiado pela meta'),
        ),
    ]
