# Generated by Django 5.2 on 2026-06-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_fk_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_transactions', to='core.creditcard', verbose_name='Cartão da fatura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_month',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mês da fatura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ano da fatura'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_card_bill',
            field=models.BooleanField(default=False, help_text='Se True, esta transação representa o pagamento da fatura e entra no fluxo de caixa.', verbose_name='É fatura de cartão'),
        ),
    ]
