# Generated by Django 5.2 on 2026-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction_card_bill_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(help_text='Ex: Nubank, MercadoPago, Inter', max_length=50, verbose_name='Nome do cartão'),
        ),
    ]
