# Generated by Django 5.2 on 2026-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_creditcard_name_max15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(help_text='Ex: Nubank, MercadoPago, Inter', max_length=25, verbose_name='Nome do cartão'),
        ),
    ]
