# Generated by Django 5.2 on 2026-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_creditcard_name_max25'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nome'),
        ),
    ]
